export const RUBROS_BASE = [
  { nombre: 'Trabajos preliminares', orden: 1 },
  { nombre: 'Demoliciones', orden: 2 },
  { nombre: 'Excavaciones', orden: 3 },
  { nombre: 'Albañilería', orden: 4 },
  { nombre: 'Hormigón armado', orden: 5 },
  { nombre: 'Cubiertas', orden: 6 },
  { nombre: 'Aislaciones', orden: 7 },
  { nombre: 'Revoques', orden: 8 },
  { nombre: 'Contrapisos y carpetas', orden: 9 },
  { nombre: 'Revestimientos', orden: 10 },
  { nombre: 'Pisos', orden: 11 },
  { nombre: 'Cielorrasos', orden: 12 },
  { nombre: 'Carpinterías', orden: 13 },
  { nombre: 'Pinturas', orden: 14 },
  { nombre: 'Instalaciones', orden: 15, hijos: [
    { nombre: 'Sanitarias', orden: 1 },
    { nombre: 'Gas', orden: 2 },
    { nombre: 'Eléctrica', orden: 3 },
    { nombre: 'Termomecánica', orden: 4 },
  ]},
  { nombre: 'Equipamiento', orden: 16 },
  { nombre: 'Limpieza final', orden: 17 },
];
